version: '3.0.0'
services:
  mongo-block1:
    container_name: "mongo-block1"
    image: "mongo:4.4.13"
    ports:
      - "27018:27017"
    networks:
      cluster1:
        ipv4_address: 192.168.100.2
    volumes:
      - blockchain:/home/block1/data/db

  mongo-block2:
    container_name: "mongo-block2"
    image: "mongo:4.4.13"
    ports:
      - "27019:27017"
    networks:
      cluster2:
        ipv4_address: 192.168.200.2
    volumes:
      - blockchain:/home/block2/data/db
  
  block-serve1:
    container_name: "block-serve1"
    build: .
    environment:
      - DB_URL=192.168.100.2
    ports:
      - "3000:3000"
    networks:
      cluster1:
        ipv4_address: 192.168.100.3
      blocknet:
        ipv4_address: 192.168.50.2

  block-serve2:
    container_name: "block-serve2"
    build: .
    environment:
      - DB_URL=192.168.200.2
    ports:
      - "8002:3000"
    networks:
      cluster2:
        ipv4_address: 192.168.200.3
      blocknet:
        ipv4_address: 192.168.50.3

networks:
  cluster1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
  cluster2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24
  blocknet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.50.0/24

volumes:
  blockchain: